arb-dir: lib/core/l10n/arb
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
output-dir: lib/core/l10n/app_localizations
untranslated-messages-file: l10n_errors.txt